// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr69DIkiuz0bENdziiE3u1s_Tv892rIN8',
    appId: '1:181668953837:web:f1556ad97262b6f05296e4',
    messagingSenderId: '181668953837',
    projectId: 'gpgold-91ad9',
    authDomain: 'gpgold-91ad9.firebaseapp.com',
    storageBucket: 'gpgold-91ad9.firebasestorage.app',
    measurementId: 'G-80DGBMJGXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB7zNl09ElJTJlCC9GwFMVyC9Zzrrg194',
    appId: '1:181668953837:android:e27a97cfe5f5c0385296e4',
    messagingSenderId: '181668953837',
    projectId: 'gpgold-91ad9',
    storageBucket: 'gpgold-91ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgebHmCLk1HGvpsXZRexmhqseDHyB1UZ8',
    appId: '1:181668953837:ios:093e3365239f93c65296e4',
    messagingSenderId: '181668953837',
    projectId: 'gpgold-91ad9',
    storageBucket: 'gpgold-91ad9.firebasestorage.app',
    iosBundleId: 'com.gdgold.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgebHmCLk1HGvpsXZRexmhqseDHyB1UZ8',
    appId: '1:181668953837:ios:093e3365239f93c65296e4',
    messagingSenderId: '181668953837',
    projectId: 'gpgold-91ad9',
    storageBucket: 'gpgold-91ad9.firebasestorage.app',
    iosBundleId: 'com.gdgold.ios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr69DIkiuz0bENdziiE3u1s_Tv892rIN8',
    appId: '1:181668953837:web:ebe0d93739d254435296e4',
    messagingSenderId: '181668953837',
    projectId: 'gpgold-91ad9',
    authDomain: 'gpgold-91ad9.firebaseapp.com',
    storageBucket: 'gpgold-91ad9.firebasestorage.app',
    measurementId: 'G-Y0S87WM53N',
  );

}